/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as PrivateStatisticsRouteImport } from './routes/_private/statistics'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PrivatePlatformsRouteImport } from './routes/_private/platforms'
import { Route as PrivateChannelsRouteImport } from './routes/_private/channels'
import { Route as PrivateArchitecturesRouteImport } from './routes/_private/architectures'
import { Route as PrivateApplicationsRouteImport } from './routes/_private/applications'
import { Route as PrivateSettingsIndexRouteImport } from './routes/_private/settings/index'
import { Route as PrivateSettingsTufRouteImport } from './routes/_private/settings/tuf'
import { Route as PrivateSettingsTokensRouteImport } from './routes/_private/settings/tokens'
import { Route as PrivateApplicationsAppNameRouteImport } from './routes/_private/applications/$appName'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateStatisticsRoute = PrivateStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivatePlatformsRoute = PrivatePlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateChannelsRoute = PrivateChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateArchitecturesRoute = PrivateArchitecturesRouteImport.update({
  id: '/architectures',
  path: '/architectures',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateApplicationsRoute = PrivateApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsIndexRoute = PrivateSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateSettingsRoute,
} as any)
const PrivateSettingsTufRoute = PrivateSettingsTufRouteImport.update({
  id: '/tuf',
  path: '/tuf',
  getParentRoute: () => PrivateSettingsRoute,
} as any)
const PrivateSettingsTokensRoute = PrivateSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => PrivateSettingsRoute,
} as any)
const PrivateApplicationsAppNameRoute =
  PrivateApplicationsAppNameRouteImport.update({
    id: '/$appName',
    path: '/$appName',
    getParentRoute: () => PrivateApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof PrivateApplicationsRouteWithChildren
  '/architectures': typeof PrivateArchitecturesRoute
  '/channels': typeof PrivateChannelsRoute
  '/platforms': typeof PrivatePlatformsRoute
  '/settings': typeof PrivateSettingsRouteWithChildren
  '/statistics': typeof PrivateStatisticsRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/applications/$appName': typeof PrivateApplicationsAppNameRoute
  '/settings/tokens': typeof PrivateSettingsTokensRoute
  '/settings/tuf': typeof PrivateSettingsTufRoute
  '/settings/': typeof PrivateSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof PrivateApplicationsRouteWithChildren
  '/architectures': typeof PrivateArchitecturesRoute
  '/channels': typeof PrivateChannelsRoute
  '/platforms': typeof PrivatePlatformsRoute
  '/statistics': typeof PrivateStatisticsRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/applications/$appName': typeof PrivateApplicationsAppNameRoute
  '/settings/tokens': typeof PrivateSettingsTokensRoute
  '/settings/tuf': typeof PrivateSettingsTufRoute
  '/settings': typeof PrivateSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/applications': typeof PrivateApplicationsRouteWithChildren
  '/_private/architectures': typeof PrivateArchitecturesRoute
  '/_private/channels': typeof PrivateChannelsRoute
  '/_private/platforms': typeof PrivatePlatformsRoute
  '/_private/settings': typeof PrivateSettingsRouteWithChildren
  '/_private/statistics': typeof PrivateStatisticsRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_private/applications/$appName': typeof PrivateApplicationsAppNameRoute
  '/_private/settings/tokens': typeof PrivateSettingsTokensRoute
  '/_private/settings/tuf': typeof PrivateSettingsTufRoute
  '/_private/settings/': typeof PrivateSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/architectures'
    | '/channels'
    | '/platforms'
    | '/settings'
    | '/statistics'
    | '/signin'
    | '/signup'
    | '/applications/$appName'
    | '/settings/tokens'
    | '/settings/tuf'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/architectures'
    | '/channels'
    | '/platforms'
    | '/statistics'
    | '/signin'
    | '/signup'
    | '/applications/$appName'
    | '/settings/tokens'
    | '/settings/tuf'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/applications'
    | '/_private/architectures'
    | '/_private/channels'
    | '/_private/platforms'
    | '/_private/settings'
    | '/_private/statistics'
    | '/_public/signin'
    | '/_public/signup'
    | '/_private/applications/$appName'
    | '/_private/settings/tokens'
    | '/_private/settings/tuf'
    | '/_private/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/statistics': {
      id: '/_private/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof PrivateStatisticsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/platforms': {
      id: '/_private/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PrivatePlatformsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/channels': {
      id: '/_private/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof PrivateChannelsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/architectures': {
      id: '/_private/architectures'
      path: '/architectures'
      fullPath: '/architectures'
      preLoaderRoute: typeof PrivateArchitecturesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/applications': {
      id: '/_private/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof PrivateApplicationsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings/': {
      id: '/_private/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof PrivateSettingsIndexRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
    '/_private/settings/tuf': {
      id: '/_private/settings/tuf'
      path: '/tuf'
      fullPath: '/settings/tuf'
      preLoaderRoute: typeof PrivateSettingsTufRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
    '/_private/settings/tokens': {
      id: '/_private/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof PrivateSettingsTokensRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
    '/_private/applications/$appName': {
      id: '/_private/applications/$appName'
      path: '/$appName'
      fullPath: '/applications/$appName'
      preLoaderRoute: typeof PrivateApplicationsAppNameRouteImport
      parentRoute: typeof PrivateApplicationsRoute
    }
  }
}

interface PrivateApplicationsRouteChildren {
  PrivateApplicationsAppNameRoute: typeof PrivateApplicationsAppNameRoute
}

const PrivateApplicationsRouteChildren: PrivateApplicationsRouteChildren = {
  PrivateApplicationsAppNameRoute: PrivateApplicationsAppNameRoute,
}

const PrivateApplicationsRouteWithChildren =
  PrivateApplicationsRoute._addFileChildren(PrivateApplicationsRouteChildren)

interface PrivateSettingsRouteChildren {
  PrivateSettingsTokensRoute: typeof PrivateSettingsTokensRoute
  PrivateSettingsTufRoute: typeof PrivateSettingsTufRoute
  PrivateSettingsIndexRoute: typeof PrivateSettingsIndexRoute
}

const PrivateSettingsRouteChildren: PrivateSettingsRouteChildren = {
  PrivateSettingsTokensRoute: PrivateSettingsTokensRoute,
  PrivateSettingsTufRoute: PrivateSettingsTufRoute,
  PrivateSettingsIndexRoute: PrivateSettingsIndexRoute,
}

const PrivateSettingsRouteWithChildren = PrivateSettingsRoute._addFileChildren(
  PrivateSettingsRouteChildren,
)

interface PrivateRouteChildren {
  PrivateApplicationsRoute: typeof PrivateApplicationsRouteWithChildren
  PrivateArchitecturesRoute: typeof PrivateArchitecturesRoute
  PrivateChannelsRoute: typeof PrivateChannelsRoute
  PrivatePlatformsRoute: typeof PrivatePlatformsRoute
  PrivateSettingsRoute: typeof PrivateSettingsRouteWithChildren
  PrivateStatisticsRoute: typeof PrivateStatisticsRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateApplicationsRoute: PrivateApplicationsRouteWithChildren,
  PrivateArchitecturesRoute: PrivateArchitecturesRoute,
  PrivateChannelsRoute: PrivateChannelsRoute,
  PrivatePlatformsRoute: PrivatePlatformsRoute,
  PrivateSettingsRoute: PrivateSettingsRouteWithChildren,
  PrivateStatisticsRoute: PrivateStatisticsRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicSigninRoute: typeof PublicSigninRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSigninRoute: PublicSigninRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
