name: "Dispatch: Repository"

on:
  repository_dispatch:
    types: [test-build, release-push]

permissions:
  actions: write

jobs:
  build:
    uses: ./.github/workflows/auto-build.yaml
    with:
      branch: ${{ github.event.client_payload.branch || (github.event.action == 'test-build' && 'new-test') || 'release' }}
      env: ${{ github.event.client_payload.env || (github.event.action == 'test-build' && 'test') || 'prod' }}
      package: ${{ github.event.client_payload.package || 'all' }}
      platform: ${{ github.event.client_payload.platform || 'all' }}
      base_url: ${{ github.event.client_payload.base_url || (github.event.action == 'test-build' && 'https://ttpos-test1.ttpos.com/api/v1') || 'https://api.ttpos.com/api/v1' }}
      base_ws_url: ${{ github.event.client_payload.base_ws_url || (github.event.action == 'test-build' && 'wss://ttpos-test1.ttpos.com/ws') || 'wss://api.ttpos.com/ws' }}
      faynosync: ${{ github.event.client_payload.faynosync || (github.event.action == 'test-build' && 'force') || 'off' }}
    secrets: inherit
